version: '3'
services:

  #PHP
  urlshortner_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: vivasoft/php:8.0
    container_name: urlshortner_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    ports:
      - "1215:1215"
      - "9000:9000"
    volumes:
      - ./_source_/:/var/www
      - ./php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    networks:
      - app-network

  #Nginx
  urlshortner_webserver:
    image: nginx:latest
    container_name: urlshortner_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8042:80"
      - "8842:8080"
      - "44342:443"
    volumes:
      - ./_source_/:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./log/nginx/:/var/log/nginx/
    networks:
      - app-network

  #MySQL
  urlshortner_db:
    image: mysql:5.7.33
    container_name: urlshortner_db
    restart: unless-stopped
    tty: true
    ports:
      - "33016:3306"
    environment:
      MYSQL_DATABASE: emm
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

  # Mongo Server
  urlshortner_mongo:
    image: mongo:latest
    container_name: urlshortner_mongo
    restart: always
    ports:
      - "27042:27017"
    environment:
      MONGO_INITDB_DATABASE: emm
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - datadb:/data/db
    networks:
      - app-network

  # Mongo Server
  urlshortner_mongo_express:
    image: mongo-express
    container_name: urlshortner_mongo_express
    restart: always
    ports:
      - "8022:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: urlshortner_mongo
      ME_CONFIG_BASICAUTH_USERNAME: mongo
      ME_CONFIG_BASICAUTH_PASSWORD: secret
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    networks:
      - app-network

  #REDIS
  urlshortner_redis:
    image: redis:latest
    container_name: urlshortner_redis
    ports:
      - "63743:6379"
    networks:
      - app-network

  urlshortner_mailhog:
    image: mailhog/mailhog
    container_name: urlshortner_mailhog
    restart: always
    ports:
      - "10242:1025"
      - "60242:8025"
    networks:
      - app-network

#Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
  datadb:
    driver: local
